In [1]:
import numpy as np

## Array Creation

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.random.rand(3,3)

array([[0.43453413, 0.75793325, 0.97716736],
       [0.52104042, 0.31424867, 0.59539471],
       [0.35669015, 0.92155239, 0.30487895]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
arr=np.array([1,2,3,4,5,6])

In [12]:
arr

array([1, 2, 3, 4, 5, 6])

## Array Manipulation

In [13]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2=np.arange(8,14)

In [15]:
arr2.reshape(2,3)

array([[ 8,  9, 10],
       [11, 12, 13]])

In [16]:
np.concatenate([arr,arr2],axis=0)

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13])

In [22]:
arr1=np.arange(1,10).reshape(3,3)

In [23]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2=np.arange(10,19).reshape(3,3)

In [25]:
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [27]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [28]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [29]:
np.expand_dims(arr1,axis=0)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [30]:
arr1.swapaxes(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Indexing and Filtering

In [31]:
arr1[1,2]

6

In [33]:
arr1[1,:]

array([4, 5, 6])

In [35]:
arr[arr>3]

array([4, 5, 6])

In [40]:
np.nonzero(arr1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [41]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr1[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr1[:,1:2]

array([[2],
       [5],
       [8]])

In [44]:
arr1[arr1%2==0]

array([2, 4, 6, 8])

## Statistics

In [46]:
np.mean(arr1)

5.0

In [49]:
np.median(arr1)

5.0

In [50]:
np.std(arr1)

2.581988897471611

In [51]:
np.sum(arr1)

45

In [52]:
np.min(arr1)

1

In [53]:
np.max(arr1)

9

In [55]:
np.percentile(arr1,50)

5.0

In [56]:
np.var(arr1)

6.666666666666667

In [57]:
np.corrcoef(arr1,arr2)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## Linear Algebra

In [58]:
np.dot(arr1,arr2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [59]:
arr1@arr2

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [60]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [61]:
np.linalg.inv(arr1)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [62]:
np.linalg.det(arr1)

6.66133814775094e-16

In [63]:
np.linalg.eig(arr1)

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -4.22209278e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))

In [64]:
np.linalg.svd(arr1)

SVDResult(U=array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]]), S=array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]), Vh=array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]]))

In [65]:
np.linalg.norm(arr1)

16.881943016134134

## Data Handling

In [67]:
np.unique(arr1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.sort(arr1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.argsort(arr1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [72]:
np.count_nonzero(arr1)

9

In [73]:
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [74]:
np.nan_to_num(arr1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.delete(arr1,2)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [77]:
np.insert(arr1,2,10)

array([ 1,  2, 10,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
## Load an array from a CSV file
np.loadtxt('file.txt',delimiter=',')

## THANKS